added buckets to the output
Sefiraat/Networks pull request #108
Opened 2022-09-29 15:46 UTC by J3fftw1

please squash these commits

2022-09-29 15:51 UTC, TheBusyBiscuit requested changes

2022-09-29 15:51 UTC, TheBusyBiscuit commented on src/main/java/io/github/sefiraat/networks/slimefun/network/NetworkVanillaGrabber.java
> +            } else if (inventory instanceof BrewerInventory brewerInventory) {
indentation
```suggestion
        } else if (inventory instanceof BrewerInventory brewerInventory) {
```

2022-09-29 15:56 UTC, TheBusyBiscuit approved these changes

2022-10-03 07:56 UTC, Sefiraat approved these changes

2023-03-02 10:05 UTC, Sefiraat approved these changes

2023-03-06 19:24 UTC, J3fftw1 commented
@Sefiraat 👀

2023-03-11 11:03 UTC, merged